apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The base defines ALL resources shared across every environment.
# Overlays (local, dev, staging, prod) will patch on top of this.
resources:
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml