apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: local
spec:
  provider:
    vault:
      # Vault service URL inside the cluster
      # "vault" is the service name, "vault" is the namespace
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"       # The KV engine path we enabled
      version: "v2"        # KV v2 supports versioning

      auth:
        # Authenticate using the token we stored in the vault-token K8s secret
        tokenSecretRef:
          name: vault-token       # The K8s secret name
          namespace: local
          key: token              # The key inside that secret